[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://eth-sepolia.g.alchemy.com/v2/sbqHpezL4bUJUsfM5BMOG5FPeHcQ_1qQ"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 100
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 3484476
PoEAddr = "0xFd06E4269a1D9Bde43A7EeDd275Bbd28c6A766ef"
BridgeAddr = "0xfD0160288864CF09e3dD1fA3Ad1Fe2B34F09E153"
GlobalExitRootManAddr = "0x54E967b977210Bb20bD9c77c5FA3C9aaCC296ECe"
MaticAddr = "0x3b11C06B3Aac6D0f2bc676FBaD2Ca0313935e770"
L2BridgeAddrs = ["0xfD0160288864CF09e3dD1fA3Ad1Fe2B34F09E153"]
L1ChainID = 11155111