
[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
FreeClaimGasLimit = 1500000
MaxTxBytesSize=30132
MaxTxDataBytesSize=30000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
	[Pool.DB]
	User = "pool_user"
	Password = "pool_password"
	Name = "pool_db"
	Host = "zkevm-pool-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[Etherman]
URL = "https://eth-sepolia.g.alchemy.com/v2/sbqHpezL4bUJUsfM5BMOG5FPeHcQ_1qQ"
L1ChainID = 11155111
PoEAddr = "0xFd06E4269a1D9Bde43A7EeDd275Bbd28c6A766ef"
MaticAddr = "0x44720A8AA78BB4BdEa9D220aD5bC8187adCCc289"
GlobalExitRootManagerAddr = "0x54E967b977210Bb20bD9c77c5FA3C9aaCC296ECe"
MultiGasProvider = false
	[Etherman.Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
BroadcastURI = "127.0.0.1:61090"
DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
EnableL2SuggestedGasPricePolling = true
	[RPC.WebSockets]
		Enabled = true
		Port = 8133

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 100
GenBlockNumber = 3484476
trustedSequencerURL = ""

[Sequencer]
WaitPeriodPoolIsEmpty = "1s"
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
BlocksAmountForTxsToBeDeleted = 100
FrequencyToCheckTxsForDelete = "12h"
MaxTxsPerBatch = 150
MaxBatchBytesSize = 129848
MaxCumulativeGasUsed = 30000000
MaxKeccakHashes = 468
MaxPoseidonHashes = 279620
MaxPoseidonPaddings = 149796
MaxMemAligns = 262144
MaxArithmetics = 262144
MaxBinaries = 262144
MaxSteps = 8388608
WeightBatchBytesSize = 1
WeightCumulativeGasUsed = 1
WeightKeccakHashes = 1
WeightPoseidonHashes = 1
WeightPoseidonPaddings = 1
WeightMemAligns = 1
WeightArithmetics = 1
WeightBinaries = 1
WeightSteps = 1
TxLifetimeCheckTimeout = "10m"
MaxTxLifetime = "3h"
MaxTxSizeForL1 = 131072
	[Sequencer.Finalizer]
		GERDeadlineTimeoutInSec = "2s"
		ForcedBatchDeadlineTimeoutInSec = "60s"
		SendingToL1DeadlineTimeoutInSec = "20s"
		SleepDurationInMs = "100ms"
		ResourcePercentageToCloseBatch = 10
		GERFinalityNumberOfBlocks = 0
		ClosingSignalsManagerWaitForCheckingL1Timeout = "10s"
		ClosingSignalsManagerWaitForCheckingGER = "10s"
		ClosingSignalsManagerWaitForCheckingForcedBatches = "10s"
		ForcedBatchesFinalityNumberOfBlocks = 0
		SenderAddress = "0xAcB1847B82789968BFC8B1D5A295B392AC5C99B7"
		PrivateKeys = [{Path = "/pk/sequencer.keystore", Password = "testonly"}]
	[Sequencer.DBManager]
		PoolRetrievalInterval = "500ms"

[Aggregator]
Host = "0.0.0.0"
Port = 50081
ForkId = 1
RetryTime = "5s"
VerifyProofInterval = "30s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "0x3b599274eC73a72A93E2d59Cb0D2987e8bA95d5b"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"

[EthTxManager]
ForcedGas = 0
PrivateKeys = [
	{Path = "/pk/sequencer.keystore", Password = "testonly"},
	{Path = "/pk/aggregator.keystore", Password = "testonly"}
]

[L2GasPriceSuggester]
Type = "follower"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 1000000000

[MTClient]
URI  = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[BroadcastServer]
Host = "0.0.0.0"
Port = 61090

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true
